In [2]:
import numpy as np
import scipy
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

# NumPy

In [5]:
array = np.array([[ 1,  2,  3],
                  [ 4,  5,  6],
                  [ 7,  8,  9],
                  [10, 11, 12]])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
array.ndim

2

In [7]:
array.shape

(4, 3)

In [8]:
array.size

12

In [10]:
array.dtype

dtype('int32')

In [11]:
array.itemsize

4

In [14]:
array.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
array.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [20]:
np.array([1,2,3,4]).shape

(4,)

In [24]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
np.random.rand(2,3)

array([[ 0.8444043 ,  0.53627779,  0.33798264],
       [ 0.73769557,  0.57400599,  0.99452698]])

In [30]:
np.ones((3, 4), dtype=np.bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [31]:
i = np.eye(4)

In [37]:
random_numbers = np.random.rand(4, 4)
random_numbers

array([[ 0.80656818,  0.89986089,  0.18718624,  0.85797985],
       [ 0.38243694,  0.14001997,  0.45510947,  0.04823099],
       [ 0.17031476,  0.85730177,  0.64971176,  0.00215927],
       [ 0.07005305,  0.01376369,  0.27771272,  0.43065805]])

In [38]:
i * random_numbers

array([[ 0.80656818,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.14001997,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.64971176,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.43065805]])

In [39]:
np.matmul(i, random_numbers)

array([[ 0.80656818,  0.89986089,  0.18718624,  0.85797985],
       [ 0.38243694,  0.14001997,  0.45510947,  0.04823099],
       [ 0.17031476,  0.85730177,  0.64971176,  0.00215927],
       [ 0.07005305,  0.01376369,  0.27771272,  0.43065805]])

In [40]:
random_numbers

array([[ 0.80656818,  0.89986089,  0.18718624,  0.85797985],
       [ 0.38243694,  0.14001997,  0.45510947,  0.04823099],
       [ 0.17031476,  0.85730177,  0.64971176,  0.00215927],
       [ 0.07005305,  0.01376369,  0.27771272,  0.43065805]])

In [41]:
random_numbers > 0.5

array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]], dtype=bool)

In [48]:
numbers = (np.random.rand(12) * 100).astype(np.int64) 

In [49]:
numbers

array([82, 19,  8, 25, 21, 50, 27, 32, 15, 63, 45, 74], dtype=int64)

In [52]:
numbers[[2, 3,5]]

array([ 8, 25, 50], dtype=int64)

In [54]:
numbers[numbers > 40]

array([82, 50, 63, 45, 74], dtype=int64)

In [55]:
random_numbers[random_numbers>0.5]

array([ 0.80656818,  0.89986089,  0.85797985,  0.85730177,  0.64971176])

In [57]:
(random_numbers > 0.5) * random_numbers

array([[ 0.80656818,  0.89986089,  0.        ,  0.85797985],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.85730177,  0.64971176,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [60]:
random_numbers + np.array([1,2,3,4])

array([[ 1.80656818,  2.89986089,  3.18718624,  4.85797985],
       [ 1.38243694,  2.14001997,  3.45510947,  4.04823099],
       [ 1.17031476,  2.85730177,  3.64971176,  4.00215927],
       [ 1.07005305,  2.01376369,  3.27771272,  4.43065805]])

In [61]:
random_numbers + np.array([[1],[2],[3],[4]])

array([[ 1.80656818,  1.89986089,  1.18718624,  1.85797985],
       [ 2.38243694,  2.14001997,  2.45510947,  2.04823099],
       [ 3.17031476,  3.85730177,  3.64971176,  3.00215927],
       [ 4.07005305,  4.01376369,  4.27771272,  4.43065805]])

In [65]:
np.hstack([np.random.rand(2,3) , np.eye(2)])

array([[ 0.83205095,  0.82712107,  0.79004303,  1.        ,  0.        ],
       [ 0.51292049,  0.40012857,  0.23006967,  0.        ,  1.        ]])

In [66]:
np.ravel(np.eye(3))

array([ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.])

In [68]:
np.linspace(10, 20, 4)

array([ 10.        ,  13.33333333,  16.66666667,  20.        ])

In [76]:
random_numbers.mean(axis=0)

array([ 0.35734323,  0.47773658,  0.39243005,  0.33475704])

In [72]:
random_numbers.mean(axis=1)

array([ 0.68789879,  0.25644934,  0.41987189,  0.19804688])

In [78]:
np.cos(random_numbers)

array([[ 0.69197999,  0.62171893,  0.98253175,  0.65396709],
       [ 0.92775797,  0.99021321,  0.89821292,  0.99883711],
       [ 0.98553147,  0.65447993,  0.7962582 ,  0.99999767],
       [ 0.99754729,  0.99990528,  0.96168503,  0.90869123]])

In [82]:
def my_func(x):
    return x**2 + 2*x + 1

my_func(0.38)

1.9043999999999999

In [80]:
my_func(random_numbers)

array([[ 3.26368857,  3.60947139,  1.40941118,  3.45208911],
       [ 1.91113191,  1.29964552,  2.11734356,  1.09878821],
       [ 1.36963664,  3.44956985,  2.72154889,  1.0043232 ],
       [ 1.14501353,  1.02771682,  1.6325498 ,  2.04678245]])

In [85]:
matrix = np.arange(1, 10).reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [87]:
matrix @ np.eye(3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [91]:
(random_numbers @ np.linalg.inv(random_numbers)).round(2)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1., -0., -0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -0., -0.,  1.]])

# SciPy